export const FETCH_COMMENT_LIKES_PENDING = 'FETCH_COMMENT_LIKES_PENDING';
export const FETCH_COMMENT_LIKES_FULFILLED = 'FETCH_COMMENT_LIKES_FULFILLED';
export const FETCH_COMMENT_LIKES_REJECTED = 'FETCH_COMMENT_LIKES_REJECTED';