export const FETCH_COMMENTATOR_PENDING = 'FETCH_COMMENTATOR_PENDING';
export const FETCH_COMMENTATOR_FULFILLED = 'FETCH_COMMENTATOR_FULFILLED';
export const FETCH_COMMENTATOR_REJECTED = 'FETCH_COMMENTATOR_REJECTED';