// добавить лайк комментарию
export const ADD_COMMENT_LIKE_PENDING = 'ADD_COMMENT_LIKE_PENDING';
export const ADD_COMMENT_LIKE_FULFILLED = 'ADD_COMMENT_LIKE_FULFILLED';
export const ADD_COMMENT_LIKE_REJECTED = 'ADD_COMMENT_LIKE_REJECTED';
// удалить лайк с комментария
export const DELETE_COMMENT_LIKE_PENDING = 'DELETE_COMMENT_LIKE_PENDING';
export const DELETE_COMMENT_LIKE_FULFILLED = 'DELETE_COMMENT_LIKE_FULFILLED';
export const DELETE_COMMENT_LIKE_REJECTED = 'DELETE_COMMENT_LIKE_REJECTED';