export const FETCH_FEED_POSTS_SAMPLE_PENDING = 'FETCH_FEED_POSTS_SAMPLE_PENDING';
export const FETCH_FEED_POSTS_SAMPLE_FULFILLED = 'FETCH_FEED_POSTS_SAMPLE_FULFILLED';
export const FETCH_FEED_POSTS_SAMPLE_REJECTED = 'FETCH_FEED_POSTS_SAMPLE_REJECTED';