// получить выборку подписчиков для автоподгрузки
export const FETCH_USER_FOLLOWERS_SAMPLE_PENDING = 'FETCH_USER_FOLLOWERS_SAMPLE_PENDING';
export const FETCH_USER_FOLLOWERS_SAMPLE_FULFILLED = 'FETCH_USER_FOLLOWERS_SAMPLE_FULFILLED';
export const FETCH_USER_FOLLOWERS_SAMPLE_REJECTED = 'FETCH_USER_FOLLOWERS_SAMPLE_REJECTED';

// добавить подписчика
export const ADD_USER_FOLLOWER_PENDING = 'ADD_USER_FOLLOWER_PENDING';
export const ADD_USER_FOLLOWER_FULFILLED = 'ADD_USER_FOLLOWER_FULFILLED';
export const ADD_USER_FOLLOWER_REJECTED = 'ADD_USER_FOLLOWER_REJECTED';

// удалить подписчика
export const DELETE_USER_FOLLOWER_PENDING = 'DELETE_USER_FOLLOWER_PENDING';
export const DELETE_USER_FOLLOWER_FULFILLED = 'DELETE_USER_FOLLOWER_FULFILLED';
export const DELETE_USER_FOLLOWER_REJECTED = 'DELETE_USER_FOLLOWER_REJECTED';