export const FETCH_LOGIN_PENDING = 'FETCH_LOGIN_PENDING';
export const FETCH_LOGIN_FULFILLED = 'FETCH_LOGIN_FULFILLED';
export const FETCH_LOGIN_REJECTED = 'FETCH_LOGIN_REJECTED';
export const UNLOGGED_PENDING = 'UNLOGGED_PENDING';
export const UNLOGGED_FULFILLED = 'UNLOGGED_FULFILLED';
export const UNLOGGED_REJECTED = 'UNLOGGED_REJECTED';