export const FETCH_LOGIN_PENDING = 'FETCH_LOGIN_PENDING';
export const FETCH_LOGIN_FULFILLED = 'FETCH_LOGIN_FULFILLED';
export const FETCH_LOGIN_REJECTED = 'FETCH_LOGIN_REJECTED';

export const UNLOGGED_PENDING = 'UNLOGGED_PENDING';
export const UNLOGGED_FULFILLED = 'UNLOGGED_FULFILLED';
export const UNLOGGED_REJECTED = 'UNLOGGED_REJECTED';

export const EDIT_USER_PENDING = 'EDIT_USER_PENDING';
export const EDIT_USER_FULFILLED = 'EDIT_USER_FULFILLED';
export const EDIT_USER_REJECTED = 'EDIT_USER_REJECTED';