// получить выборку отзывов для автоподгрузки
export const FETCH_OPINIONS_SAMPLE_PENDING = 'FETCH_OPINIONS_SAMPLE_PENDING';
export const FETCH_OPINIONS_SAMPLE_FULFILLED = 'FETCH_OPINIONS_SAMPLE_FULFILLED';
export const FETCH_OPINIONS_SAMPLE_REJECTED = 'FETCH_OPINIONS_SAMPLE_REJECTED';

// добавить отзыв
export const ADD_OPINION_PENDING = 'ADD_OPINION_PENDING';
export const ADD_OPINION_FULFILLED = 'ADD_OPINION_FULFILLED';
export const ADD_OPINION_REJECTED = 'ADD_OPINION_REJECTED';
