//export const FETCH_POST_LIKES_PENDING = 'FETCH_POST_LIKES_PENDING';
//export const FETCH_POST_LIKES_FULFILLED = 'FETCH_POST_LIKES_FULFILLED';
//export const FETCH_POST_LIKES_REJECTED = 'FETCH_POST_LIKES_REJECTED';

export const ADD_POST_LIKE_PENDING = 'ADD_POST_LIKE_PENDING';
export const ADD_POST_LIKE_FULFILLED = 'ADD_POST_LIKE_FULFILLED';
export const ADD_POST_LIKE_REJECTED = 'ADD_POST_LIKE_REJECTED';

export const DELETE_POST_LIKE_PENDING = 'DELETE_POST_LIKE_PENDING';
export const DELETE_POST_LIKE_FULFILLED = 'DELETE_POST_LIKE_FULFILLED';
export const DELETE_POST_LIKE_REJECTED = 'DELETE_POST_LIKE_REJECTED';