export const FETCH_POSTS_SAMPLE_PENDING = 'FETCH_POSTS_SAMPLE_PENDING';
export const FETCH_POSTS_SAMPLE_FULFILLED = 'FETCH_POSTS_SAMPLE_FULFILLED';
export const FETCH_POSTS_SAMPLE_REJECTED = 'FETCH_POSTS_SAMPLE_REJECTED';

export const DELETE_POST_PENDING = 'DELETE_POST_PENDING';
export const DELETE_POST_FULFILLED = 'DELETE_POST_FULFILLED';
export const DELETE_POST_REJECTED = 'DELETE_POST_REJECTED';