// добавить лайк посту
export const ADD_POST_LIKE_PENDING = 'ADD_POST_LIKE_PENDING';
export const ADD_POST_LIKE_FULFILLED = 'ADD_POST_LIKE_FULFILLED';
export const ADD_POST_LIKE_REJECTED = 'ADD_POST_LIKE_REJECTED';

// удалить лайк с поста
export const DELETE_POST_LIKE_PENDING = 'DELETE_POST_LIKE_PENDING';
export const DELETE_POST_LIKE_FULFILLED = 'DELETE_POST_LIKE_FULFILLED';
export const DELETE_POST_LIKE_REJECTED = 'DELETE_POST_LIKE_REJECTED';