export const FETCH_TOP_POSTS_PENDING = 'FETCH_TOP_POSTS_PENDING';
export const FETCH_TOP_POSTS_FULFILLED = 'FETCH_TOP_POSTS_FULFILLED';
export const FETCH_TOP_POSTS_REJECTED = 'FETCH_TOP_POSTS_REJECTED';