// получить выборку комментариев к посту для автпподгрузки
export const FETCH_POST_COMMENTS_SAMPLE_PENDING = 'FETCH_POST_COMMENTS_SAMPLE_PENDING';
export const FETCH_POST_COMMENTS_SAMPLE_FULFILLED = 'FETCH_POST_COMMENTS_SAMPLE_FULFILLED';
export const FETCH_POST_COMMENTS_SAMPLE_REJECTED = 'FETCH_POST_COMMENTS_SAMPLE_REJECTED';

// добавить комментарий
export const ADD_POST_COMMENT_PENDING = 'ADD_POST_COMMENT_PENDING';
export const ADD_POST_COMMENT_FULFILLED = 'ADD_POST_COMMENT_FULFILLED';
export const ADD_POST_COMMENT_REJECTED = 'ADD_POST_COMMENT_REJECTED';

// удалить комментарий
export const DELETE_POST_COMMENT_PENDING = 'DELETE_POST_COMMENT_PENDING';
export const DELETE_POST_COMMENT_FULFILLED = 'DELETE_POST_COMMENT_FULFILLED';
export const DELETE_POST_COMMENT_REJECTED = 'DELETE_POST_COMMENT_REJECTED';