export const FETCH_POST_COMMENTS_PENDING = 'FETCH_POST_COMMENTS_PENDING';
export const FETCH_POST_COMMENTS_FULFILLED = 'FETCH_POST_COMMENTS_FULFILLED';
export const FETCH_POST_COMMENTS_REJECTED = 'FETCH_POST_COMMENTS_REJECTED';