export const FETCH_POST_LIKES_PENDING = 'FETCH_POST_LIKES_PENDING';
export const FETCH_POST_LIKES_FULFILLED = 'FETCH_POST_LIKES_FULFILLED';
export const FETCH_POST_LIKES_REJECTED = 'FETCH_POST_LIKES_REJECTED';