// получить выборку подписок пользователя для автоподгрузки
export const FETCH_USER_SUBS_SAMPLE_PENDING = 'FETCH_USER_SUBS_SAMPLE_PENDING';
export const FETCH_USER_SUBS_SAMPLE_FULFILLED = 'FETCH_USER_SUBS_SAMPLE_FULFILLED';
export const FETCH_USER_SUBS_SAMPLE_REJECTED = 'FETCH_USER_SUBS_SAMPLE_REJECTED';

// удалить подписку
export const DELETE_USER_SUB_PENDING = 'DELETE_USER_SUB_PENDING';
export const DELETE_USER_SUB_FULFILLED = 'DELETE_USER_SUB_FULFILLED';
export const DELETE_USER_SUB_REJECTED = 'DELETE_USER_SUB_REJECTED';