export const FETCH_USER_SUBSCRIBES_SAMPLE_PENDING = 'FETCH_USER_SUBSCRIBES_SAMPLE_PENDING';
export const FETCH_USER_SUBSCRIBES_SAMPLE_FULFILLED = 'FETCH_USER_SUBSCRIBES_SAMPLE_FULFILLED';
export const FETCH_USER_SUBSCRIBES_SAMPLE_REJECTED = 'FETCH_USER_SUBSCRIBES_SAMPLE_REJECTED';

export const ADD_USER_SUBSCRIBE_PENDING = 'ADD_USER_SUBSCRIBE_PENDING';
export const ADD_USER_SUBSCRIBE_FULFILLED = 'ADD_USER_SUBSCRIBE_FULFILLED';
export const ADD_USER_SUBSCRIBE_REJECTED = 'ADD_USER_SUBSCRIBE_REJECTED';

export const DELETE_USER_SUBSCRIBE_PENDING = 'DELETE_USER_SUBSCRIBE_PENDING';
export const DELETE_USER_SUBSCRIBE_FULFILLED = 'DELETE_USER_SUBSCRIBE_FULFILLED';
export const DELETE_USER_SUBSCRIBE_REJECTED = 'DELETE_USER_SUBSCRIBE_REJECTED';