// получить топ отмеченных постов пользователя
export const FETCH_TOP_LIKES_POSTS_PENDING = 'FETCH_TOP_LIKES_POSTS_PENDING';
export const FETCH_TOP_LIKES_POSTS_FULFILLED = 'FETCH_TOP_LIKES_POSTS_FULFILLED';
export const FETCH_TOP_LIKES_POSTS_REJECTED = 'FETCH_TOP_LIKES_POSTS_REJECTED';

// удалить пост со станицы Рейтинги
export const DELETE_TOP_LIKES_POST_PENDING = 'DELETE_TOP_LIKES_POST_PENDING';
export const DELETE_TOP_LIKES_POST_FULFILLED = 'DELETE_TOP_LIKES_POST_FULFILLED';
export const DELETE_TOP_LIKES_POST_REJECTED = 'DELETE_TOP_LIKES_POST_REJECTED';
