export const FETCH_TOP_VIEWS_POSTS_PENDING = 'FETCH_TOP_VIEWS_POSTS_PENDING';
export const FETCH_TOP_VIEWS_POSTS_FULFILLED = 'FETCH_TOP_VIEWS_POSTS_FULFILLED';
export const FETCH_TOP_VIEWS_POSTS_REJECTED = 'FETCH_TOP_VIEWS_POSTS_REJECTED';

export const DELETE_TOP_VIEWS_POST_PENDING = 'DELETE_TOP_VIEWS_POST_PENDING';
export const DELETE_TOP_VIEWS_POST_FULFILLED = 'DELETE_TOP_VIEWS_POST_FULFILLED';
export const DELETE_TOP_VIEWS_POST_REJECTED = 'DELETE_TOP_VIEWS_POST_REJECTED';


