// получить выборку пользователей для автоподгрузки
export const FETCH_USERS_SAMPLE_PENDING = 'FETCH_USERS_SAMPLE_PENDING';
export const FETCH_USERS_SAMPLE_FULFILLED = 'FETCH_USERS_SAMPLE_FULFILLED';
export const FETCH_USERS_SAMPLE_REJECTED = 'FETCH_USERS_SAMPLE_REJECTED';

// зарегистрировать пользователя
export const REGISTER_USER_PENDING = 'REGISTER_USER_PENDING';
export const REGISTER_USER_FULFILLED = 'REGISTER_USER_FULFILLED';
export const REGISTER_USER_REJECTED = 'REGISTER_USER_REJECTED';