// получить выборку постов пользователя для автоподгрузки
export const FETCH_USER_POSTS_SAMPLE_PENDING = 'FETCH_USER_POSTS_SAMPLE_PENDING';
export const FETCH_USER_POSTS_SAMPLE_FULFILLED = 'FETCH_USER_POSTS_SAMPLE_FULFILLED';
export const FETCH_USER_POSTS_SAMPLE_REJECTED = 'FETCH_USER_POSTS_SAMPLE_REJECTED';

// добавить пост
export const ADD_USER_POST_PENDING = 'ADD_USER_POST_PENDING';
export const ADD_USER_POST_FULFILLED = 'ADD_USER_POST_FULFILLED';
export const ADD_USER_POST_REJECTED = 'ADD_USER_POST_REJECTED';
